#!/bin/bash
echo -e "Willkommen zu Level 03!"
echo -e "Dieses Level ist zu Testzwecken automatisch bestanden."
echo -e "Prüfe den erfolgreichen Abschluss mit dem Befehl 'verify'."
echo -e "Um diesen Hinweis erneut zu sehen, nutze den Befehl 'showtask'."
